# Generated by Django 6.0.6 on 2026-06-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('search', 'Поиск исполнителя'), ('work', 'В работе'), ('delivered', 'Сдача результата'), ('review', 'Приём'), ('closed', 'Закрыт'), ('dispute', 'Оспаривание')], default='draft', max_length=20, verbose_name='Статус')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/', verbose_name='Файл результата')),
                ('result_comment', models.TextField(blank=True, verbose_name='Комментарий к результату')),
                ('client', models.ForeignKey(limit_choices_to={'client_profile_isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='taskrs_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executor', models.ForeignKey(limit_choices_to={'executor_profile_isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Закказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=20, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'Истории заказов',
            },
        ),
    ]
