# Generated by Django 6.0.6 on 2026-06-14 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(limit_choices_to={'client_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='taskrs_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(limit_choices_to={'executor_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/', verbose_name='Файл результата')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Материал задачи',
                'verbose_name_plural': 'Материалы задачи',
            },
        ),
    ]
