# Generated by Django 6.0.6 on 2026-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_result_file_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
