# Generated by Django 6.0.6 on 2026-07-04 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, limit_choices_to={'executor_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
