# Generated by Django 6.0.6 on 2026-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskmaterial_created_at_alter_taskmaterial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
    ]
